backend:
  name: github
  repo: unochifarah/unochifarah.github.io
  branch: main
  auth_type: implicit
  app_id: Ov23lic4NIeEr67R92BV

media_folder: "images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }

  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
